{{- if and .Values.grafana.enabled .Values.grafana.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: {{ include "monitoring.ns" . }}  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.pvc.size }}
{{- end -}}