{{- if .Values.promtail.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: {{ include "monitoring.ns" . }}
data:
  config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /positions/positions.yaml

    clients:
      - url: http://loki.monitoring:3100/loki/api/v1/push

    scrape_configs:
      - job_name: files-direct-default
        static_configs:
          - targets: [localhost]
            labels:
              job: files-direct-default
              namespace: default
              __path__: /var/log/containers/*_default_*-*.log

        pipeline_stages:
          - regex:
              source: filename
              expression: '.*/(?P<pod>(?P<app>backend|frontend)-[^_]+)_default_(?P<container>[^-]+)-.*\.log'

          - labels:
              app:
              pod:
              container:

          - docker: {}
{{- end -}}