name: Backend (Разработка и доставка)

permissions:
  contents: read
  packages: write

on:
  push:
    branches: ["develop"]
    paths:
      - "backend/**"
      - ".github/workflows/backend-action.yml"

  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/backend-action.yml"

env:
  IMAGE_NAME: backend
  DOCKERFILE: backend/Dockerfile
  CONTEXT_DIR: backend
  VERSION: 1.0.${{ github.run_number }}

jobs:
  test_backend:
    name: Test backend (Go)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum

      - name: Run tests
        run: |
          cd backend
          go test ./...

  build_and_push:
    name: Docker build & push (backend)
    needs: test_backend
    if: github.event_name == 'push' && github.ref_name == 'develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Repo name to lowercase
        run: echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set VERSION_TAG
        run: echo "VERSION_TAG=${{ env.VERSION }}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (VERSION tag)
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT_DIR }}
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}

      - name: Build & push (latest)
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT_DIR }}
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/${{ env.IMAGE_NAME }}:latest

  helm_chart:
    name: Helm chart (backend)
    runs-on: ubuntu-latest
    container:
      image: alpine/helm:4.0.4
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      CHART_PATH: infrastructure/helm/backend
      OWNER: ${{ github.repository_owner }}
      CHART_NAME: backend
    needs: build_and_push
    if: github.event_name == 'push' && github.ref_name == 'develop'
    steps:
      - uses: actions/checkout@v4

      - name: Owner to lowercase
        run: echo "OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GHCR 
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login $REGISTRY \
            --username ${{ github.actor }} \
            --password-stdin

      - name: Helm lint (strict) 
        run: helm lint $CHART_PATH --strict

      - name: Package Helm Chart
        run: |
          helm package $CHART_PATH \
            --version "${{ env.VERSION }}" \
            --app-version "${{ env.VERSION }}" \
            --destination dist

      - name: Push Helm Chart to GHCR 
        run: |
          helm push dist/*.tgz oci://$REGISTRY/$OWNER_LOWER/helm

  notify_telegram:
    name: Notify Telegram (after build)
    runs-on: ubuntu-latest
    needs: helm_chart
    if: github.event_name == 'push' && github.ref_name == 'develop'
    steps:
      - name: Notify Telegram
        if: always()
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MSG: |
            ✅ ${{ github.workflow }} завершен
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Автор: ${{ github.actor }}
            Статус: ${{ job.status }}
            Ссылка: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Подготовлена версия: ${{ env.VERSION }} сервиса backend! Не забудьте установить переменную в окружении: https://github.com/MonstroKosilka/final/settings/environments/11498833788/edit
        run: |
          curl -sS -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            --data-urlencode "chat_id=${CHAT_ID}" \
            --data-urlencode "text=${MSG}" \
            --data-urlencode "disable_web_page_preview=true"

  notify_telegram_2:
    name: Notify Telegram (PR -> main)
    runs-on: ubuntu-latest
    needs: test_backend
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    steps:
      - name: Notify Telegram
        if: always()
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MSG: |
            ⏳ ${{ github.workflow }} ожидает ручного одобрения на DEPLOY
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Автор: ${{ github.actor }}
            Статус: ${{ job.status }}
            Ссылка: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl -sS -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            --data-urlencode "chat_id=${CHAT_ID}" \
            --data-urlencode "text=${MSG}" \
            --data-urlencode "disable_web_page_preview=true"

  deploy:
    name: Deploy (only PR -> main)
    runs-on: ubuntu-latest
    needs: notify_telegram_2
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    environment: deploy
    steps:
      - name: DEPLOY
        run: |
          echo "Deploy triggered by PR into main"
          echo "Deploy version backend: ${{ vars.BACKEND_VERSION }}!"
